### ISSUE TITLE
fillEqually not work when use ForEach in UVStack

### ISSUE THREAD

**Issue by EkkoG** [MihaelIsaev/UIKitPlus#31]
This works well

```
        view.body {
            UVStack {
                UView().background(.random)
                UView().background(.random)
                UView().background(.random)
            }.edgesToSuperview().alignment(.fill).distribution(.fillEqually)
        }
```
![Simulator Screen Shot - iPhone 11 - 2022-04-19 at 00 41 09](https://user-images.githubusercontent.com/3138493/163841458-d8f091b9-1789-4456-ad22-675c47d73308.png)

This will not work.
```
        view.body {
            UVStack {
                UForEach([0, 1, 2]) { i in
                    UText("识别结果, \(i)").background(.random)
                }
            }.edgesToSuperview().alignment(.fill).distribution(.fillEqually)
        }
```

![image](https://user-images.githubusercontent.com/3138493/163841492-d36c3c92-257c-4f1c-bfb2-ed3d7ccb30cc.png)

**Comment by MihaelIsaev** [comment]
@EkkoG this fix should work, please don't hesitate to re-open the issue if it doesn't
