### ISSUE TITLE
needs example for list , tableview

### ISSUE THREAD

**Issue by madadoux** [MihaelIsaev/UIKitPlus#4]
Hi mihaellsaev 
you did an awesome work on this repo 
I really needed it for long time 
I really love the previews 
**You are awesome!!!**
please update the description of the rest of class's

**Comment by MihaelIsaev** [comment]
@madadoux first of all thank you! 🙏
I'd propose an example project https://github.com/MihaelIsaev/UIKitPlusExample it contains `tableView` example with diffable data source.
Also it would be cool if you could join our little community https://discord.gg/q5wCPYv ❤️ here I'm online all the time and can help with everything 🚀
